In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Final_verification_sheet1.xlsx', header=[0, 1, 2])

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df

                      Input table
    Inputs for logical operations           Inputs for addition
                          Hex2Bin Hex2Bin.1             Number1 Number2
0                            AB01         A                  46      13  \
1                            AB02         A                  32       8
2                            AB03         A                  38      12
3                            AB04         A                  55      16
4                            AB05         A                  52      16
..                            ...       ...                 ...     ...
135                          AD36         B                  46      11
136                          AD37         B                  45      12
137                          AD38         B                  24       4
138                          AE49         B                  62      18
139                          AE50         B                  56      18


    Inputs for multiplication         Inputs for division
                      Number1 Number2             Divisor Dividend
0                           3       6                  23      168  \
1                           3       4                  17      115
2                           3       6                  23      172
3                           3       8                  23      199
4                           3       7                  23      195
..                        ...     ...                 ...      ...
135                         3       6                  23      186
136                         3       6                  23      170
137                         0       0                   6       44
138                         3      10                  20      172
139                         3       8                  23      201

       Name of student
    Unnamed: 8_level_1
    Unnamed: 8_level_2
0             Student1  \
1             Student2
2             Student3
3             Student4
4             Student5
..                 ...
135         Student136
136         Student137
137         Student138
138         Student139
139         Student140

                                              Verification sheet
    These to be verified and results to be printed in top folder
                                         Addition to be verified
0                                                   59            \
1                                                   40
2                                                   50
3                                                   71
4                                                   68
..                                                 ...
135                                                 57
136                                                 57
137                                                 32
138                                                 80
139                                                 74



    Test remark(Pass/Fail) Division to be verified Test remark(Pass/Fail).1
0                      NaN                      18                      NaN  \
1                      NaN                      12                      NaN
2                      NaN                      18                      NaN
3                      NaN                      24                      NaN
4                      NaN                      20                      NaN
..                     ...                     ...                      ...
135                    NaN                      18                      NaN
136                    NaN                      18                      NaN
137                    NaN                       0                      NaN
138                    NaN                      30                      NaN
139                    NaN                      24                      NaN



    Multiplication to be verified Test remark(Pass/Fail).2
0                            7.30                      NaN  \
1                            0.00                      NaN
2                            7.48                      NaN
3                            8.65                      NaN
4                            8.48                      NaN
..                            ...                      ...
135                          8.09                      NaN
136                          7.39                      NaN
137                          0.00                      NaN
138                          0.00                      NaN
139                          8.74                      NaN

                                            Output table
    Binary Operation to be printed in subsequent foldera
                                                     AND NAND  OR NOR XOR XNOR
0                                                  NaN    NaN NaN NaN NaN  NaN
1                                                  NaN    NaN NaN NaN NaN  NaN
2                                                  NaN    NaN NaN NaN NaN  NaN
3                                                  NaN    NaN NaN NaN NaN  NaN
4                                                  NaN    NaN NaN NaN NaN  NaN
..                                                 ...    ...  ..  ..  ..  ...
135                                                NaN    NaN NaN NaN NaN  NaN
136                                                NaN    NaN NaN NaN NaN  NaN
137                                                NaN    NaN NaN NaN NaN  NaN
138                                                NaN    NaN NaN NaN NaN  NaN
139                                                NaN    NaN NaN NaN NaN  NaN

[140 rows x 21 columns]

In [5]:
a1=df.loc[:, ('Input table', 'Inputs for addition', 'Number1')]
a2=df.loc[:, ('Input table', 'Inputs for addition', 'Number2')]
ver=df.loc[:, ('Verification sheet','These to be verified and results to be printed in top folder', 'Addition to be verified')]
a_result = a1+a2
remark = df.loc[:, ('Verification sheet','These to be verified and results to be printed in top folder', 'Test remark(Pass/Fail)')]

In [6]:
remark[a_result == ver] = 'Pass'
remark[a_result != ver] = 'Fail'

C:\Users\Om\AppData\Local\Temp/ipykernel_17868/1663171322.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remark[a_result == ver] = 'Pass'

In [7]:
remark

0      Pass
1      Pass
2      Pass
3      Pass
4      Pass
       ...
135    Pass
136    Pass
137    Fail
138    Pass
139    Pass
Name: (Verification sheet, These to be verified and results to be printed in top folder, Test remark(Pass/Fail)), Length: 140, dtype: object

In [8]:
df

                      Input table
    Inputs for logical operations           Inputs for addition
                          Hex2Bin Hex2Bin.1             Number1 Number2
0                            AB01         A                  46      13  \
1                            AB02         A                  32       8
2                            AB03         A                  38      12
3                            AB04         A                  55      16
4                            AB05         A                  52      16
..                            ...       ...                 ...     ...
135                          AD36         B                  46      11
136                          AD37         B                  45      12
137                          AD38         B                  24       4
138                          AE49         B                  62      18
139                          AE50         B                  56      18


    Inputs for multiplication         Inputs for division
                      Number1 Number2             Divisor Dividend
0                           3       6                  23      168  \
1                           3       4                  17      115
2                           3       6                  23      172
3                           3       8                  23      199
4                           3       7                  23      195
..                        ...     ...                 ...      ...
135                         3       6                  23      186
136                         3       6                  23      170
137                         0       0                   6       44
138                         3      10                  20      172
139                         3       8                  23      201

       Name of student
    Unnamed: 8_level_1
    Unnamed: 8_level_2
0             Student1  \
1             Student2
2             Student3
3             Student4
4             Student5
..                 ...
135         Student136
136         Student137
137         Student138
138         Student139
139         Student140

                                              Verification sheet
    These to be verified and results to be printed in top folder
                                         Addition to be verified
0                                                   59            \
1                                                   40
2                                                   50
3                                                   71
4                                                   68
..                                                 ...
135                                                 57
136                                                 57
137                                                 32
138                                                 80
139                                                 74



    Test remark(Pass/Fail) Division to be verified Test remark(Pass/Fail).1
0                     Pass                      18                      NaN  \
1                     Pass                      12                      NaN
2                     Pass                      18                      NaN
3                     Pass                      24                      NaN
4                     Pass                      20                      NaN
..                     ...                     ...                      ...
135                   Pass                      18                      NaN
136                   Pass                      18                      NaN
137                   Fail                       0                      NaN
138                   Pass                      30                      NaN
139                   Pass                      24                      NaN



    Multiplication to be verified Test remark(Pass/Fail).2
0                            7.30                      NaN  \
1                            0.00                      NaN
2                            7.48                      NaN
3                            8.65                      NaN
4                            8.48                      NaN
..                            ...                      ...
135                          8.09                      NaN
136                          7.39                      NaN
137                          0.00                      NaN
138                          0.00                      NaN
139                          8.74                      NaN

                                            Output table
    Binary Operation to be printed in subsequent foldera
                                                     AND NAND  OR NOR XOR XNOR
0                                                  NaN    NaN NaN NaN NaN  NaN
1                                                  NaN    NaN NaN NaN NaN  NaN
2                                                  NaN    NaN NaN NaN NaN  NaN
3                                                  NaN    NaN NaN NaN NaN  NaN
4                                                  NaN    NaN NaN NaN NaN  NaN
..                                                 ...    ...  ..  ..  ..  ...
135                                                NaN    NaN NaN NaN NaN  NaN
136                                                NaN    NaN NaN NaN NaN  NaN
137                                                NaN    NaN NaN NaN NaN  NaN
138                                                NaN    NaN NaN NaN NaN  NaN
139                                                NaN    NaN NaN NaN NaN  NaN

[140 rows x 21 columns]

In [9]:
m1=df.loc[:, ('Input table', 'Inputs for multiplication', 'Number1')]
m2=df.loc[:, ('Input table', 'Inputs for multiplication', 'Number2')]
ver=df.loc[:, ('Verification sheet', 'These to be verified and results to be printed in top folder', 'Multiplication to be verified')]
m_result = m1*m2
remark = df.loc[:, ('Verification sheet', 'These to be verified and results to be printed in top folder', 'Test remark(Pass/Fail).2')]

In [10]:
remark[m_result == ver] = 'Pass'
remark[m_result != ver] = 'Fail'

C:\Users\Om\AppData\Local\Temp/ipykernel_17868/637300713.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remark[m_result == ver] = 'Pass'

In [11]:
df

                      Input table
    Inputs for logical operations           Inputs for addition
                          Hex2Bin Hex2Bin.1             Number1 Number2
0                            AB01         A                  46      13  \
1                            AB02         A                  32       8
2                            AB03         A                  38      12
3                            AB04         A                  55      16
4                            AB05         A                  52      16
..                            ...       ...                 ...     ...
135                          AD36         B                  46      11
136                          AD37         B                  45      12
137                          AD38         B                  24       4
138                          AE49         B                  62      18
139                          AE50         B                  56      18


    Inputs for multiplication         Inputs for division
                      Number1 Number2             Divisor Dividend
0                           3       6                  23      168  \
1                           3       4                  17      115
2                           3       6                  23      172
3                           3       8                  23      199
4                           3       7                  23      195
..                        ...     ...                 ...      ...
135                         3       6                  23      186
136                         3       6                  23      170
137                         0       0                   6       44
138                         3      10                  20      172
139                         3       8                  23      201

       Name of student
    Unnamed: 8_level_1
    Unnamed: 8_level_2
0             Student1  \
1             Student2
2             Student3
3             Student4
4             Student5
..                 ...
135         Student136
136         Student137
137         Student138
138         Student139
139         Student140

                                              Verification sheet
    These to be verified and results to be printed in top folder
                                         Addition to be verified
0                                                   59            \
1                                                   40
2                                                   50
3                                                   71
4                                                   68
..                                                 ...
135                                                 57
136                                                 57
137                                                 32
138                                                 80
139                                                 74



    Test remark(Pass/Fail) Division to be verified Test remark(Pass/Fail).1
0                     Pass                      18                      NaN  \
1                     Pass                      12                      NaN
2                     Pass                      18                      NaN
3                     Pass                      24                      NaN
4                     Pass                      20                      NaN
..                     ...                     ...                      ...
135                   Pass                      18                      NaN
136                   Pass                      18                      NaN
137                   Fail                       0                      NaN
138                   Pass                      30                      NaN
139                   Pass                      24                      NaN



    Multiplication to be verified Test remark(Pass/Fail).2
0                            7.30                     Fail  \
1                            0.00                     Fail
2                            7.48                     Fail
3                            8.65                     Fail
4                            8.48                     Fail
..                            ...                      ...
135                          8.09                     Fail
136                          7.39                     Fail
137                          0.00                     Pass
138                          0.00                     Fail
139                          8.74                     Fail

                                            Output table
    Binary Operation to be printed in subsequent foldera
                                                     AND NAND  OR NOR XOR XNOR
0                                                  NaN    NaN NaN NaN NaN  NaN
1                                                  NaN    NaN NaN NaN NaN  NaN
2                                                  NaN    NaN NaN NaN NaN  NaN
3                                                  NaN    NaN NaN NaN NaN  NaN
4                                                  NaN    NaN NaN NaN NaN  NaN
..                                                 ...    ...  ..  ..  ..  ...
135                                                NaN    NaN NaN NaN NaN  NaN
136                                                NaN    NaN NaN NaN NaN  NaN
137                                                NaN    NaN NaN NaN NaN  NaN
138                                                NaN    NaN NaN NaN NaN  NaN
139                                                NaN    NaN NaN NaN NaN  NaN

[140 rows x 21 columns]

In [12]:
d1=df.loc[:, ('Input table', 'Inputs for division', 'Divisor')]
d2=df.loc[:, ('Input table', 'Inputs for division', 'Dividend')]
ver=df.loc[:, ('Verification sheet', 'These to be verified and results to be printed in top folder', 'Division to be verified')]
d_result= d1/d2
remark = df.loc[:, ('Verification sheet', 'These to be verified and results to be printed in top folder', 'Test remark(Pass/Fail).1')]

In [13]:
remark[d_result==ver]='Pass'
remark[d_result!=ver]='Fail'

C:\Users\Om\AppData\Local\Temp/ipykernel_17868/1883607132.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remark[d_result==ver]='Pass'
C:\Users\Om\AppData\Local\Temp/ipykernel_17868/1883607132.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  remark[d_result!=ver]='Fail'

In [14]:
df

                      Input table
    Inputs for logical operations           Inputs for addition
                          Hex2Bin Hex2Bin.1             Number1 Number2
0                            AB01         A                  46      13  \
1                            AB02         A                  32       8
2                            AB03         A                  38      12
3                            AB04         A                  55      16
4                            AB05         A                  52      16
..                            ...       ...                 ...     ...
135                          AD36         B                  46      11
136                          AD37         B                  45      12
137                          AD38         B                  24       4
138                          AE49         B                  62      18
139                          AE50         B                  56      18


    Inputs for multiplication         Inputs for division
                      Number1 Number2             Divisor Dividend
0                           3       6                  23      168  \
1                           3       4                  17      115
2                           3       6                  23      172
3                           3       8                  23      199
4                           3       7                  23      195
..                        ...     ...                 ...      ...
135                         3       6                  23      186
136                         3       6                  23      170
137                         0       0                   6       44
138                         3      10                  20      172
139                         3       8                  23      201

       Name of student
    Unnamed: 8_level_1
    Unnamed: 8_level_2
0             Student1  \
1             Student2
2             Student3
3             Student4
4             Student5
..                 ...
135         Student136
136         Student137
137         Student138
138         Student139
139         Student140

                                              Verification sheet
    These to be verified and results to be printed in top folder
                                         Addition to be verified
0                                                   59            \
1                                                   40
2                                                   50
3                                                   71
4                                                   68
..                                                 ...
135                                                 57
136                                                 57
137                                                 32
138                                                 80
139                                                 74



    Test remark(Pass/Fail) Division to be verified Test remark(Pass/Fail).1
0                     Pass                      18                     Fail  \
1                     Pass                      12                     Fail
2                     Pass                      18                     Fail
3                     Pass                      24                     Fail
4                     Pass                      20                     Fail
..                     ...                     ...                      ...
135                   Pass                      18                     Fail
136                   Pass                      18                     Fail
137                   Fail                       0                     Fail
138                   Pass                      30                     Fail
139                   Pass                      24                     Fail



    Multiplication to be verified Test remark(Pass/Fail).2
0                            7.30                     Fail  \
1                            0.00                     Fail
2                            7.48                     Fail
3                            8.65                     Fail
4                            8.48                     Fail
..                            ...                      ...
135                          8.09                     Fail
136                          7.39                     Fail
137                          0.00                     Pass
138                          0.00                     Fail
139                          8.74                     Fail

                                            Output table
    Binary Operation to be printed in subsequent foldera
                                                     AND NAND  OR NOR XOR XNOR
0                                                  NaN    NaN NaN NaN NaN  NaN
1                                                  NaN    NaN NaN NaN NaN  NaN
2                                                  NaN    NaN NaN NaN NaN  NaN
3                                                  NaN    NaN NaN NaN NaN  NaN
4                                                  NaN    NaN NaN NaN NaN  NaN
..                                                 ...    ...  ..  ..  ..  ...
135                                                NaN    NaN NaN NaN NaN  NaN
136                                                NaN    NaN NaN NaN NaN  NaN
137                                                NaN    NaN NaN NaN NaN  NaN
138                                                NaN    NaN NaN NaN NaN  NaN
139                                                NaN    NaN NaN NaN NaN  NaN

[140 rows x 21 columns]

In [236]:
a = df['Input table']['Inputs for logical operations']['Hex2Bin']
b = df['Input table']['Inputs for logical operations']['Hex2Bin.1']
a_bin=[]
b_bin=[]
for i in a:
    binary=bin(int(i, 16))[2:]
    a_bin.append(binary)
    
for i in b:
    binary=bin(int(i, 16))[2:]
    b_bin.append(binary)

b_bin = [n.zfill(16) for n in b_bin]

A = pd.Series(a_bin)
B = pd.Series(b_bin)

In [181]:
#logical_and
result=[]
for i in range(len(a_bin)):
    and_result=''
    for j in range(len(a_bin[i])):
        and_result += str(int(a_bin[i][j]) & int(b_bin[i][j]))
    result.append(and_result)
a = []
for i in result:
    groups = [i[j:j+4] for j in range(0, len(i), 4)]
    hex_digits=''
    for group in groups:
        hex_digits += hex(int(group, 2))[2:]
    ans = hex_digits[3:]
    a.append(ans)
AND = pd.Series(a)
df.loc[:, ('Output table', 'Binary Operation to be printed in subsequent foldera', 'AND')]= AND

In [201]:
#logical_OR
result=[]
for i in range(len(a_bin)):
    or_result=''
    for j in range(len(a_bin[i])):
        or_result += str(int(a_bin[i][j]) | int(b_bin[i][j]))
    result.append(or_result)
a = []
for i in result:
    groups = [i[j:j+4] for j in range(0, len(i), 4)]
    hex_digits=''
    for group in groups:
        hex_digits += hex(int(group, 2))[2:]
    ans = hex_digits
    a.append(ans)
OR = pd.Series(a)
df.loc[:, ('Output table', 'Binary Operation to be printed in subsequent foldera', 'OR')]= OR

In [229]:
#logical_NOR
l=[]
for i in OR:
    nor_val = hex(~int(i, 16) & 0xFFFF)[2:]
    l.append(nor_val)
NOR = pd.Series(l)
df.loc[:, ('Output table', 'Binary Operation to be printed in subsequent foldera', 'NOR')]= NOR

In [231]:
#logical_NAND
l=[]
for i in AND:
    nand_val = hex(~int(i, 16) & 0xFFFF)[2:]
    l.append(nand_val)
NAND = pd.Series(l)
df.loc[:, ('Output table', 'Binary Operation to be printed in subsequent foldera', 'NAND')]= NAND

In [197]:
#logical_XOR
result=[]
for i in range(len(a_bin)):
    xor_result=''
    for j in range(len(a_bin[i])):
        xor_result += str(int(a_bin[i][j]) ^ int(b_bin[i][j]))
    result.append(xor_result)
a = []
for i in result:
    groups = [i[j:j+4] for j in range(0, len(i), 4)]
    hex_digits=''
    for group in groups:
        hex_digits += hex(int(group, 2))[2:]
    ans = hex_digits
    a.append(ans)
XOR = pd.Series(a)
df.loc[:, ('Output table', 'Binary Operation to be printed in subsequent foldera', 'XOR')]= XOR

In [233]:
#logical_XNOR
l=[]
for i in XOR:
    nand_val = hex(~int(i, 16) & 0xFFFF)[2:]
    l.append(nand_val)
XNOR = pd.Series(l)
df.loc[:, ('Output table', 'Binary Operation to be printed in subsequent foldera', 'XNOR')]= XNOR

In [234]:
df

                      Input table
    Inputs for logical operations           Inputs for addition
                          Hex2Bin Hex2Bin.1             Number1 Number2
0                            AB01         A                  46      13  \
1                            AB02         A                  32       8
2                            AB03         A                  38      12
3                            AB04         A                  55      16
4                            AB05         A                  52      16
..                            ...       ...                 ...     ...
135                          AD36         B                  46      11
136                          AD37         B                  45      12
137                          AD38         B                  24       4
138                          AE49         B                  62      18
139                          AE50         B                  56      18


    Inputs for multiplication         Inputs for division
                      Number1 Number2             Divisor Dividend
0                           3       6                  23      168  \
1                           3       4                  17      115
2                           3       6                  23      172
3                           3       8                  23      199
4                           3       7                  23      195
..                        ...     ...                 ...      ...
135                         3       6                  23      186
136                         3       6                  23      170
137                         0       0                   6       44
138                         3      10                  20      172
139                         3       8                  23      201

       Name of student
    Unnamed: 8_level_1
    Unnamed: 8_level_2
0             Student1  \
1             Student2
2             Student3
3             Student4
4             Student5
..                 ...
135         Student136
136         Student137
137         Student138
138         Student139
139         Student140

                                              Verification sheet
    These to be verified and results to be printed in top folder
                                         Addition to be verified
0                                                   59            \
1                                                   40
2                                                   50
3                                                   71
4                                                   68
..                                                 ...
135                                                 57
136                                                 57
137                                                 32
138                                                 80
139                                                 74



    Test remark(Pass/Fail) Division to be verified Test remark(Pass/Fail).1
0                     Pass                      18                     Fail  \
1                     Pass                      12                     Fail
2                     Pass                      18                     Fail
3                     Pass                      24                     Fail
4                     Pass                      20                     Fail
..                     ...                     ...                      ...
135                   Pass                      18                     Fail
136                   Pass                      18                     Fail
137                   Fail                       0                     Fail
138                   Pass                      30                     Fail
139                   Pass                      24                     Fail



    Multiplication to be verified Test remark(Pass/Fail).2
0                            7.30                     Fail  \
1                            0.00                     Fail
2                            7.48                     Fail
3                            8.65                     Fail
4                            8.48                     Fail
..                            ...                      ...
135                          8.09                     Fail
136                          7.39                     Fail
137                          0.00                     Pass
138                          0.00                     Fail
139                          8.74                     Fail

                                            Output table
    Binary Operation to be printed in subsequent foldera
                                                     AND  NAND    OR   NOR
0                                                    0    ffff  ab0b  54f4  \
1                                                    2    fffd  ab0a  54f5
2                                                    2    fffd  ab0b  54f4
3                                                    0    ffff  ab0e  54f1
4                                                    0    ffff  ab0f  54f0
..                                                 ...     ...   ...   ...
135                                                  2    fffd  ad3f  52c0
136                                                  3    fffc  ad3f  52c0
137                                                  8    fff7  ad3b  52c4
138                                                  9    fff6  ae4b  51b4
139                                                  0    ffff  ae5b  51a4



      XOR  XNOR
0    ab0b  54f4
1    ab08  54f7
2    ab09  54f6
3    ab0e  54f1
4    ab0f  54f0
..    ...   ...
135  ad3d  52c2
136  ad3c  52c3
137  ad33  52cc
138  ae42  51bd
139  ae5b  51a4

[140 rows x 21 columns]

## Saving the results

In [ ]:
# saving addition inputs and results as a text file
a1.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/arithmetic operation/Add/ip1.txt', header=None, index=None, sep='\n')
a2.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/arithmetic operation/Add/ip2.txt', header=None, index=None, sep='\n')
a_result.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/arithmetic operation/Add/output.txt', header=None, index=None, sep='\n')

In [ ]:
# saving multiplication inputs and results as a text file
m1.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/arithmetic operation/Multiply/ip1.txt', header=None, index=None, sep='\n')
m2.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/arithmetic operation/Multiply/ip2.txt', header=None, index=None, sep='\n')
m_result.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/arithmetic operation/Multiply/output.txt', header=None, index=None, sep='\n')

In [ ]:
# saving division inputs and results as a text file
d1.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/arithmetic operation/Divide/ip1.txt', header=None, index=None, sep='\n')
d2.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/arithmetic operation/Divide/ip2.txt', header=None, index=None, sep='\n')
d_result.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/arithmetic operation/Divide/output.txt', header=None, index=None, sep='\n')

In [237]:
# saving and inputs and results as a text file
A.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/AND/ip1.txt', header=None, index=None, sep='\n')
B.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/AND/ip2.txt', header=None, index=None, sep='\n')
AND.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/AND/output.txt', header=None, index=None, sep='\n')

In [239]:
# saving Nand inputs and results as a text file
A.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/NAND/ip1.txt', header=None, index=None, sep='\n')
B.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/NAND/ip2.txt', header=None, index=None, sep='\n')
NAND.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/NAND/output.txt', header=None, index=None, sep='\n')

In [240]:
# saving Or inputs and results as a text file
A.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/OR/ip1.txt', header=None, index=None, sep='\n')
B.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/OR/ip2.txt', header=None, index=None, sep='\n')
OR.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/OR/output.txt', header=None, index=None, sep='\n')

In [241]:
# saving Nor inputs and results as a text file
A.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/NOR/ip1.txt', header=None, index=None, sep='\n')
B.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/NOR/ip2.txt', header=None, index=None, sep='\n')
NOR.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/NOR/output.txt', header=None, index=None, sep='\n')

In [242]:
# saving Xor inputs and results as a text file
A.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/XOR/ip1.txt', header=None, index=None, sep='\n')
B.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/XOR/ip2.txt', header=None, index=None, sep='\n')
XOR.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/XOR/output.txt', header=None, index=None, sep='\n')

In [243]:
# saving Xnor inputs and results as a text file
A.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/XNOR/ip1.txt', header=None, index=None, sep='\n')
B.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/XNOR/ip2.txt', header=None, index=None, sep='\n')
XNOR.to_csv('C:/Users/Om/PycharmProjects/File Handling/venv/ALU/logical operation/XNOR/output.txt', header=None, index=None, sep='\n')

In [246]:
#Saving the final verification sheet in the top ALU folder
df.to_excel('ALU\Final_verification_sheet.xlsx')